### ISSUE TITLE
Optimize Image Sizes on Projects Page

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/grackl#93] opened 2017-12-06 16:38 UTC
**As a:** 
Site User
**Needs a way to:** 
Improve initial page load time
**So that:** 
It is usable to me more quickly
**Because:**

**Comment by mateoclarke** [comment] 2017-12-06 19:53
Thanks for adding this. Only closing bc this is a dupe of #87

**Closed by mateoclarke** 2017-12-06 19:53 UTC
Labels: duplicate
